name: Docker Build & Smoke Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build production image (multi-stage)
        run: |
          docker build -t momintrust-web:ci .

      - name: Run container in background
        run: |
          docker run -d --name momintrust-web-ci -p 8080:80 momintrust-web:ci

      - name: Wait for container to be healthy / respond
        run: |
          # Simple retry loop to hit the root endpoint
          for i in `seq 1 15`; do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 || true)
            if [ "$status" = "200" ]; then
              echo "OK"
              exit 0
            fi
            echo "Attempt $i/15 - status=$status; sleeping 2s"
            sleep 2
          done
          echo "Container didn't return HTTP 200 within timeout" >&2
          docker logs momintrust-web-ci || true
          exit 1

      - name: Cleanup
        if: always()
        run: |
          docker rm -f momintrust-web-ci || true
